kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-for-ns-admin
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list", "create", "delete", "update"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list", "create", "delete", "update"]
- apiGroups: ["apps"]  # API group for ReplicaSets and Deployments
  resources: ["replicasets", "deployments"]
  verbs: ["get", "watch", "list", "create", "delete", "update"]
