---
- name: Create a cron Job
  hosts: localhost
  tasks:
    - name: Schedule cron
      cron:
         name: This job is scheduled by Ansible
         minute: "0"
         hour: "10"
         day: "*"
         month: "*"
         weekday: "4"
         user: root
         job: "/home/ec2-user/cfile.sh"
