def groovy

pipeline {
    agent any
    stages{
        stage('code clone'){
            steps{
                echo 'Git repo cloning in progress..'
                git branch: 'main', url: 'https://github.com/thangacodes/shell-scripting.git'
            }
        }
        stage('loading groovy'){
            steps{
                script{
                    pwd
                    sleep(5)
                    groovy = load "Iac_TF/Jenkins/tf.groovy"
                }
            }
        }
        stage('init'){
            steps{
                script{
                    groovy.tfinit()
                }
            }
        }
        stage('fmt'){
            steps{
                script {
                    groovy.tffmt()
                }
            }
        }
        stage('validate'){
            steps{
                script {
                    groovy.tfvalidate()
                }
            }
        }
        stage('tf_plan'){
            steps{
                script {
                    groovy.tfplan()
                }
            }
        }
        stage('Input_before_apply'){
            input{
                message "Are we good to apply? Say yes or no?"
            }
            steps{
                echo 'Next Terraform apply will begin shortly...'
            }
        }
        stage('tf_apply'){
            steps{
                script {
                    groovy.tfapply()
                }
            }
        }
        stage('Input_before_destroy'){
            input{
                message "Are we good to destroy? Say yes or no?"
            }
            steps{
                echo 'Next Terraform destroy will begin shortly...'
            }
        }
        stage('tf_destroy'){
            steps{
                script{
                    groovy.tfdestroy()
                }
            }
        }
    }
}
